[tools]
atuin = "latest"
bat = "latest"
chezmoi = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
node = "latest"
ripgrep = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"
